apiVersion: apps/v1
kind: Deployment
metadata:
  name: b2b-uat-security
  namespace: b2b-uat
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: b2b-uat-security
  template:
    metadata:
      labels:
        app: b2b-uat-security
    spec:
      containers:
        - name: b2b-uat-security
          image: '216989138057.dkr.ecr.ap-south-1.amazonaws.com/b2b-uat-switch-security:latest'
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          # resources:
          #   requests:
          #     cpu: "250m" 
          #     memory: "256Mi"
          #   limits:
          #     cpu: "500m"
          #     memory: "512Mi"
